ElementareTeilchen:
  Fluid:
    ViewHelpers:
      Image:
        widths:
          - 100
          - 150
          - 200
          - 300
          - 400
          - 500
          - 625
          - 750
          - 1000
          - 1250
          - 1500
          - 1750
          - 2000
          - 2250
          - 2500
          - 2750
          - 3000
          - 3250
          - 3500
          - 3750
          - 4000
